name: "Deploy App Zendesk"
description: "Adds pull request file changes as a comment to a newly opened PR"
inputs:
  env:
    description: "Environment"
    required: true
    default: "develop"
  params:
    description: "Manifest params"
    required: false
  path:
    description: "Directory path"
    required: true
  zendesk_subdomain:
    description: "Zendesk subdomain where the app will be deployed"
    required: true
  zendesk_email:
    description: "Zendesk email to authenticate"
    required: true
  zendesk_api_token:
    description: "Zendesk api token to authenticate"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Set Node Version"
      run: "git update-index --chmod=+x ${{ github.action_path }}/dist/index.js"
      shell: bash

    - name: "Run auto-commit"
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        commit_message: build script with git-auto-commit
