name: "Deploy App Zendesk"
description: "Adds pull request file changes as a comment to a newly opened PR"
inputs:
  environment:
    description: "Environment"
    required: true
    default: "develop"
  params:
    description: "Manifest params"
    required: false
  path:
    description: "Directory path. Default to './'"
    required: false
  package:
    description: "App zip. Cannot be filled if 'path' parameter is filled"
    required: false
  zendesk_apps_config_path:
    description: "Path of file 'zendesk.apps.config.json'. Default to './'"
    required: false
  zendesk_subdomain:
    description: "Zendesk subdomain where the app will be deployed"
    required: true
  zendesk_email:
    description: "Zendesk email to authenticate"
    required: true
  zendesk_api_token:
    description: "Zendesk api token to authenticate"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"