name: deploy-app

on:
  push:
    branches: 
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    strategy:
      matrix:
        node-version: [16.15.1]
        working-directory: [./]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Intall Dependencies
        run: yarn

      - name: Build Action
        run: yarn build

      - name: Run auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build script with git-auto-commit